Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/index'
  get 'welcome/p2'
  get 'welcome/p3'
  get 'welcome/p4'
  get 'welcome/p5'
  get 'welcome/p6'
  get 'welcome/p7'
  get 'welcome/p8'
  get 'welcome/p9'
  get 'welcome/p10'
  get 'welcome/p11'
  get 'welcome/p12'
  root 'welcome#index'
end
